# Generated by Django 4.0.4 on 2022-05-26 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloraTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='XodimModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('brith_day', models.DateField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('lavozim', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='YangiliklarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('data', models.DateTimeField(blank=True)),
                ('image', models.ImageField(upload_to='')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FloraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('data', models.DateTimeField(blank=True)),
                ('flora_types', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ziravor.floratypemodel')),
            ],
        ),
    ]
