# Generated by Django 4.0.4 on 2022-05-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziravor', '0002_xodimmodels_facebook_xodimmodels_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xodimmodels',
            name='qabul',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xodimmodels',
            name='tel_raqam',
            field=models.IntegerField(blank=True, default=True, max_length=255),
            preserve_default=False,
        ),
    ]
