# Generated by Django 4.0.4 on 2022-05-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziravor', '0004_alter_xodimmodels_tel_raqam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xodimmodels',
            old_name='qabul',
            new_name='fullname_eng',
        ),
        migrations.RemoveField(
            model_name='floramodel',
            name='info',
        ),
        migrations.RemoveField(
            model_name='floramodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='floramodel',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='floramodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='floratypemodel',
            name='type',
        ),
        migrations.RemoveField(
            model_name='xodimmodels',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='xodimmodels',
            name='lavozim',
        ),
        migrations.RemoveField(
            model_name='yangiliklarmodel',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='yangiliklarmodel',
            name='text',
        ),
        migrations.RemoveField(
            model_name='yangiliklarmodel',
            name='title',
        ),
        migrations.AddField(
            model_name='floramodel',
            name='info_eng',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='floramodel',
            name='info_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='floramodel',
            name='info_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='floramodel',
            name='name_eng',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='floramodel',
            name='name_ru',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='floramodel',
            name='name_uz',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='floramodel',
            name='subtitle_eng',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='floramodel',
            name='subtitle_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='floramodel',
            name='subtitle_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='floramodel',
            name='title_eng',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='floramodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='floramodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='floratypemodel',
            name='type_eng',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='floratypemodel',
            name='type_ru',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='floratypemodel',
            name='type_uz',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='xodimmodels',
            name='fullname_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xodimmodels',
            name='fullname_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xodimmodels',
            name='lavozim_eng',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xodimmodels',
            name='lavozim_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xodimmodels',
            name='lavozim_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xodimmodels',
            name='qabul_eng',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xodimmodels',
            name='qabul_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='xodimmodels',
            name='qabul_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='yangiliklarmodel',
            name='sub_title_eng',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='yangiliklarmodel',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='yangiliklarmodel',
            name='sub_title_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='yangiliklarmodel',
            name='text_eng',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yangiliklarmodel',
            name='text_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yangiliklarmodel',
            name='text_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yangiliklarmodel',
            name='title_eng',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='yangiliklarmodel',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='yangiliklarmodel',
            name='title_uz',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
