# Generated by Django 4.0.4 on 2022-05-31 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ziravor', '0007_alter_floramodel_info_en_alter_floramodel_info_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floramodel',
            name='info_en',
        ),
        migrations.RemoveField(
            model_name='floramodel',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='floramodel',
            name='subtitle_en',
        ),
        migrations.RemoveField(
            model_name='floramodel',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='xodimmodels',
            name='fullname_en',
        ),
        migrations.RemoveField(
            model_name='xodimmodels',
            name='lavozim_en',
        ),
        migrations.RemoveField(
            model_name='xodimmodels',
            name='qabul_en',
        ),
        migrations.RemoveField(
            model_name='yangiliklarmodel',
            name='sub_title_en',
        ),
        migrations.RemoveField(
            model_name='yangiliklarmodel',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='yangiliklarmodel',
            name='title_en',
        ),
    ]
