# Generated by Django 4.0.4 on 2022-05-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziravor', '0008_remove_floramodel_info_en_remove_floramodel_name_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
    ]
