# Generated by Django 4.0.4 on 2022-05-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziravor', '0009_dockmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockmodel',
            name='sub_title_ru',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dockmodel',
            name='sub_title_uz',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
